### ISSUE TITLE
Vote Module Design

### ISSUE THREAD

**Issue by 4meta5** [4meta5/substrate-sauce#2]
simple vote module that should support different basic governance examples/samples; it should focus on minimal demonstration of substrate features, but I also am looking for a complete, self-contained implementation.

Here's the first draft of the trait I'm using (see the `vote` branch):
```rust
pub trait Trait: system::Trait {
    /// Overarching event type
    type Event: From<Event<Self>> + Into<<Self as system::Trait>::Event>;
    /// The balances type
    type Currency: Currency<Self::AccountId> + ReservableCurrency<Self::AccountId>;
    /// Proposal type, dispatchable from runtime methods
    type Proposal: Parameter + Dispatchable<Origin=Self::Origin>;
    /// Signal type, for representing each member's voting power
    type Signal: SimpleArithmetic + Clone + Copy + Default + FullCodec + MaybeSerializeDeserialize + Debug;
    /// Origin for decisions that only require a majority vote
    type MajorityCarries: EnsureOrigin<Self::Origin, Success=Self::AccountId>;
    /// Origin for members to cancel proposals in emergency scenarios
    type CancellationOrigin: EnsureOrigin<Self::Origin, Success=Self::AccountId>;
    /// Origin for setting a member's relative voting weight (meta, path to QV)
    type WeightOrigin: EnsureOrigin<Self::Origin, Success=Self::AccountId>;
    /// The period for which votes are counted
    type VotePeriod: Get<Self::BlockNumber>;
}
```

It is more than 6 associated types, but I think `Event` and `Currency` shouldn't add much mental overhead. Notably, there are a few `EnsureOrigin` types, each of which will require different levels of permissions from potentially different sets of actors.

## todo
After I finish the first, I'll likely make issues for the second to encourage outside contribution.
- [ ] custom origins (like democracy)
- [ ] runtime instancing (like elections)
- [ ]  offchain workers for voting (like elections-phragmen)
